# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c543a09925bf3a2dc7a3029ad2808bae2806e4fe37aac0f58bb2c4025e319b3167106456f08a1195fc5e1f0f3eb6a494c8c379baf1ddd05c31e9519bc8a79e63

test:
  secret_key_base: 560ca738e831663866f62974c763661f0ec39ef5c74ca6b3e87f504ae2ae4849dbd10a6cebad804f7575ce58e483490a5dd3d5bddfae4fd6435f7a3cc4b54242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
